import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { gql } from "@apollo/client";
import client from "../apollo-client";

export default function Home({users, bubbles}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          {users.map((user) => (
            <div key={user.name} className={styles.card}>
              <p>
                {user.name}
              </p>
            </div>
          ))}
        </div>
{/* 
        <div className={styles.grid}>
          {bubbles.map((bubble) => (
            <div key={bubble.text} className={styles.card}>
              <p>
                {bubble.text}
              </p>
            </div>
          ))}
        </div> */}

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getServerSideProps() {
  const { data } = await client.query({
    query: gql`
    query User {
      user{
        name
      }
    },
    `,
  });

  return {
    props: {
      users: data.user.slice(0, 2),
    },
 };
}

